branches:
  only:
    - master
language: c
jobs:
  include:
    - os: osx
      osx_image: xcode12.2
      install: brew install esolitos/ipa/sshpass
    - os: windows
      install:
        - choco install make
        - choco install putty
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make -f mac-Makefile release       ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then make -f win-Makefile release   ; fi

after_success:
  - export LAST_GIT_TAG_VERSION=$(git describe --abbrev=0 --tags) && export LAST_GIT_TAG_VERSION=${LAST_GIT_TAG_VERSION:1}
  - export GIT_TAG_VERSION=$((LAST_GIT_TAG_VERSION+1))

deploy:
  on:
    branch: master
    condition: -z $(git tag --points-at $TRAVIS_COMMIT)
  provider: script
  skip_cleanup: true
  script: bash ./deploy.sh
