language: c

jobs:
  include:
    - os: osx
      osx_image: xcode12.2
    - os: windows
      script: choco install make

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make -f mac-Makefile release     ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then make -f win-Makefile release ; fi
