branches:
  only:
    #- develop
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
language: c
jobs:
  include:
    - os: osx
      osx_image: xcode12.2
      install: brew install esolitos/ipa/sshpass
    - os: windows
      install:
        - choco install make
        - choco install putty
script:
  - make release
before_deploy:
  #- export MAC_FILE_PATH=build/release/pdftrick-native_1.0.1.jnilib
  #- export WIN_FILE_PATH=build/release/pdftrick-native_1.0.1.dll
  - export MAC_FILE_PATH=build/release/pdftrick-native_${TRAVIS_TAG:1}.jnilib
  - export WIN_FILE_PATH=build/release/pdftrick-native_${TRAVIS_TAG:1}.dll
deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./deploy.sh
    on:
      branch: develop
  - provider: releases
    api_key: "$GITHUB_TOKEN"
    file:
      - $MAC_FILE_PATH
      - $WIN_FILE_PATH
    skip_cleanup: true
    on:
      tags: true
