branches:
  only:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
language: c
jobs:
  include:
    - os: osx
      osx_image: xcode12.2
      install: brew install esolitos/ipa/sshpass
    - os: windows
      install:
        - choco install make
        - choco install putty
script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then make -f mac-Makefile release       ; fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then make -f win-Makefile release   ; fi

before_deploy:
  - export MAC_FILE_PATH=dist/mac/release/pdftrick-native_${TRAVIS_TAG:1}.jnilib
  - export WIN_FILE_PATH=dist/win/release/pdftrick-native_${TRAVIS_TAG:1}.dll
deploy:
  #provider: script
  #skip_cleanup: true
  #script: bash ./deploy.sh
  #on:
    #tags: true
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file: 
    - ${MAC_FILE_PATH}
    - ${WIN_FILE_PATH}
  skip_cleanup: true
  on:
    tags: true
