/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gmdev_pdftrick_nativeutil_NativeLibCall */

#ifndef _Included_org_gmdev_pdftrick_nativeutil_NativeLibCall
#define _Included_org_gmdev_pdftrick_nativeutil_NativeLibCall

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gmdev_pdftrick_nativeutil_NativeLibCall
 * Method:    renderThumbnail
 * Signature: (String, String, int, int)
 */
JNIEXPORT void JNICALL
Java_org_gmdev_pdftrick_nativeutil_NativeLibCall_renderThumbnail(
    JNIEnv *, jobject, jstring, jstring, jint, jint);

/*
 * Class:     org_gmdev_pdftrick_nativeutil_NativeLibCall
 * Method:    renderFull
 * Signature: (String, String, int, int)
 */
JNIEXPORT void JNICALL
Java_org_gmdev_pdftrick_nativeutil_NativeLibCall_renderFull(JNIEnv *, jobject,
                                                            jstring, jstring,
                                                            jint, jint);

#ifdef __cplusplus
}

#endif
#endif
