name: pdftrick-native windows
on: [push]
jobs:
  # test-windows:
  #   runs-on: windows-latest
  #   if: github.ref == 'refs/heads/develop'
  #   defaults:
  #     run:
  #       shell: msys2 {0}
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #     - name: Set up Mysys2
  #       uses: msys2/setup-msys2@v2
  #       with:
  #         update: true
  #         msystem: MINGW64
  #         install: >-
  #           pkg-config
  #           make
  #           mingw-w64-x86_64-gcc
  #           mingw-w64-x86_64-check
  #     - run: echo "Os -> ${{ runner.os }}, branch -> ${{ github.ref }}, repository -> ${{ github.repository }}."
  #     - name: Test
  #       run: make test
  test-mac:
    runs-on: macos-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup dev tools
        run: brew install check
      - name: Test
        run: make test

  deploy-windows:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Mysys2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          msystem: MINGW64
          install: >-
            pkg-config
            make
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-check
      - run: echo "Os -> ${{ runner.os }}, branch -> ${{ github.ref }}, repository -> ${{ github.repository }}."
      - name: Release
        run: make release
  
 